export const highNews = [
  {
    id: "68670bd5753499b7e5d9c486",
    title: "CSB Bank Shares Surge 3% After Q1 (First Quarter) Results",
    summary:
      "CSB Bank shares increased by 3% following a strong business update for the first quarter of financial year 2026.\nThis positive performance indicates that the bank is doing well, which can attract more investors and boost its stock price.\nIt's like a restaurant getting great reviews; more customers are likely to visit and enjoy the food.",
    url: "https://www.business-standard.com/markets/news/csb-bank-share-pops-3-on-healthy-q1-business-show-key-info-inside-125070300192_1.html",
    source: "BusinessStandard",
    published_at: "2025-07-04T19:05:49.534Z",
    date_extracted: false,
    time_ago: "6 days ago",
    categories: null,
    tags: null,
    related_stocks: null,
    impact_score: 7,
    impact_label: "High Impact",
    sentiment_score: 0.2575757575757576,
    authors: ["BusinessStandard"],
    reaction_stats: {
      bullish: 0,
      bearish: 0,
      important: 0,
      neutral: 0,
    },
    engagement: {
      likes: 0,
      comments: 0,
    },
  },
  {
    id: "6867711a1cad89aba8e20769",
    title: "Nuvama and BSE (Bombay Stock Exchange) Stocks Plunge After Ban",
    summary:
      "Nuvama's stock dropped by 7% following the Securities and Exchange Board of India (SEBI) banning Jane Street from the securities market for market manipulation.\nThis ban negatively impacts investor confidence in Nuvama and other related companies like Angel One and BSE (Bombay Stock Exchange).\nIt's like a popular restaurant losing its chef; customers may hesitate to dine there again.",
    url: "https://www.business-standard.com/markets/news/nuvama-angle-one-bse-slide-up-to-7-per-cent-after-sebi-ban-on-jane-street-125070400226_1.html",
    source: "BusinessStandard",
    published_at: "2025-07-04T19:05:49.533Z",
    date_extracted: false,
    time_ago: "6 days ago",
    categories: null,
    tags: null,
    related_stocks: null,
    impact_score: 7,
    impact_label: "High Impact",
    sentiment_score: -0.027272727272727296,
    authors: ["BusinessStandard"],
    reaction_stats: {
      bullish: 0,
      bearish: 0,
      important: 0,
      neutral: 0,
    },
    engagement: {
      likes: 0,
      comments: 0,
    },
  },
  {
    id: "6867754a5211287b1a2930ec",
    title: "Defence Stocks Surge After DAC Approval",
    summary:
      "The Defence Acquisition Council (DAC) approved 10 major capital acquisition proposals, leading to a sharp rally in defence stocks.\nThis approval boosts investor confidence in companies like Paras, Astra, and BEML, which saw increases of up to 9%.\nIt's like a sports team getting a big endorsement deal, making everyone excited about their future performance.",
    url: "https://www.business-standard.com/markets/news/dac-nod-spurs-defence-stocks-paras-astra-beml-nifty-india-defence-index-nifty50-defence-companies-bse-nse-125070400345_1.html",
    source: "BusinessStandard",
    published_at: "2025-07-04T19:05:49.533Z",
    date_extracted: false,
    time_ago: "6 days ago",
    categories: null,
    tags: null,
    related_stocks: null,
    impact_score: 7,
    impact_label: "High Impact",
    sentiment_score: 0.2727272727272727,
    authors: ["BusinessStandard"],
    reaction_stats: {
      bullish: 0,
      bearish: 0,
      important: 0,
      neutral: 0,
    },
    engagement: {
      likes: 0,
      comments: 0,
    },
  },
  {
    id: "68670bd5753499b7e5d9c485",
    title: "M&M Financial Services Shares Surge 2%",
    summary:
      "M&M Financial Services share price rose 2 percent, reaching an intraday high of ₹267.45 per share after releasing its Q1FY26 business update.\nThis increase indicates positive investor sentiment and confidence in the company's performance.\nIt's like a sports team winning a match, boosting the morale of its fans and attracting more supporters.",
    url: "https://www.business-standard.com/markets/news/mahindra-and-mahindra-financial-services-shares-rise-2-percent-after-releasing-q1fy26-business-update-125070300169_1.html",
    source: "BusinessStandard",
    published_at: "2025-07-04T19:05:49.533Z",
    date_extracted: false,
    time_ago: "6 days ago",
    categories: null,
    tags: null,
    related_stocks: null,
    impact_score: 7,
    impact_label: "High Impact",
    sentiment_score: 0.2575757575757576,
    authors: ["BusinessStandard"],
    reaction_stats: {
      bullish: 0,
      bearish: 0,
      important: 0,
      neutral: 0,
    },
    engagement: {
      likes: 0,
      comments: 0,
    },
  },
  {
    id: "68679ad58f125395ca58f92f",
    title: "Smallcap Media Stock Soars 54% in Days",
    summary:
      "Shares of Prime Focus surged 10 percent on Friday, reaching a new high of ₹175.70.\nThis dramatic increase indicates strong investor interest and could lead to further gains in the smallcap sector.\nIt's like a local bakery suddenly becoming the talk of the town after a celebrity endorsement, attracting more customers and boosting sales.",
    url: "https://www.business-standard.com/markets/news/smallcap-media-stock-soars-54-in-6-days-ranbir-kapoor-to-acquire-shares-125070400547_1.html",
    source: "BusinessStandard",
    published_at: "2025-07-04T19:05:49.533Z",
    date_extracted: false,
    time_ago: "6 days ago",
    categories: null,
    tags: null,
    related_stocks: null,
    impact_score: 7,
    impact_label: "High Impact",
    sentiment_score: 0.3181818181818181,
    authors: ["BusinessStandard"],
    reaction_stats: {
      bullish: 0,
      bearish: 0,
      important: 0,
      neutral: 0,
    },
    engagement: {
      likes: 0,
      comments: 0,
    },
  },
];
