export const data = [
  {
    authors: ["BusinessStandard"],
    categories: ["Stocks"],
    date_extracted: false,
    engagement: { comments: 3, likes: 0 },
    id: "68763b40cf5ed850865d162c",
    impact_label: "High Impact",
    impact_score: 7,
    published_at: "2025-07-16T12:22:09.218Z",
    reaction_stats: { bearish: 0, bullish: 0, important: 0, neutral: 0 },
    related_stocks: null,
    sentiment_score: 0.3409090909090909,
    source: "BusinessStandard",
    summary:
      "• Puravankara shares jumped 7 percent after the company secured a redevelopment project worth ₹2,100 crore in Mumbai.• This significant increase reflects investor confidence in the company's growth potential and future earnings• It's like a local restaurant suddenly getting a big contract to cater a major event, boosting its reputation and sales.",
    tag: "bullish",
    tags: null,
    time_ago: "16 hours ago",
    title: "Puravankara Shares Surge on Big Project",
    url: "https://www.business-standard.com/markets/news/puravankara-shares-jump-7-per-cent-on-rs-2100-crore-redevelopment-project-125070700352_1.html",
  },
  {
    authors: ["BusinessStandard"],
    categories: ["Stocks"],
    date_extracted: false,
    engagement: { comments: 2, likes: 0 },
    id: "68763b40cf5ed850865d162d",
    impact_label: "High Impact",
    impact_score: 9,
    published_at: "2025-07-16T12:22:09.218Z",
    reaction_stats: { bearish: 0, bullish: 0, important: 0, neutral: 0 },
    related_stocks: null,
    sentiment_score: 0.2954545454545454,
    source: "BusinessStandard",
    summary:
      "• L&T Finance's share price has surged by 64% since January, nearing a new high after seven years.• This significant rise is driven by the company's focus on reducing credit costs and improving asset quality in the microfinance sector.• It's like a small business that finally finds a way to cut expenses and attract more customers, leading to a big boost in sales.",
    tag: "bullish",
    tags: null,
    time_ago: "16 hours ago",
    title: "L&T Finance Stock Soars 64% This Year",
    url: "https://www.business-standard.com/markets/news/lt-finance-nears-new-high-after-7-years-stock-zooms-64-from-january-low-125070700347_1.html",
  },
];
